### ISSUE TITLE
FlywayException: No database found to handle

### ISSUE THREAD

**Issue by HaddadJoe** [open-metadata/openmetadata-helm-charts#230]
### Checks

- [X] I have checked for existing issues.
- [X] This report is about the Openmetadata Helm Chart.
- [ ] This report is about the Openmetadata Dependencies Helm Chart.

### Description

Hi we're trying to deploy the helm chart latest version 1.3.2 on a gke v1.29.2-gke.1217000.

we're getting errors
```
$ kl -f openmetadata-77bf7b64d8-gx5g6 -c run-db-migrations
Migrating the OpenMetadata Schema.
Failed to db migration due to
org.flywaydb.core.api.FlywayException: No database found to handle jdbc:postgres://10.53.*.*:5432/openmetadata_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
	at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForUrl(DatabaseTypeRegister.java:54)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1087)
	at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:636)
	at org.openmetadata.service.util.OpenMetadataOperations.parseConfig(OpenMetadataOperations.java:411)
	at org.openmetadata.service.util.OpenMetadataOperations.migrate(OpenMetadataOperations.java:208)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2066)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.openmetadata.service.util.OpenMetadataOperations.main(OpenMetadataOperations.java:500)
```
IP masked with * but it's returning the correct one

this is our helm chart configuration
```
    database:
      host: 10.53.*.*
      port: 5432
      driverClass: org.postgresql.Driver
      dbScheme: postgres
      databaseName: openmetadata_db
      auth:
        username: openmetadata_user
        password:
          secretRef: postgres-secrets
          secretKey: openmetadata-postgres-password
```
The secret exists and the key of that secret matches the secretKey. We can reach the database from that cluster from another pod on the same box

```
$ psql -h 10.53.*.* -U openmetadata_user -d openmetadata_db
Password for user openmetadata_user:
psql (13.14 (Debian 13.14-0+deb11u1), server 14.10)
WARNING: psql major version 13, server major version 14.
         Some psql features might not work.
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

openmetadata_db=>
```

Reading a bit online, it seems like flyway needs to be complied with postgres included now? Any directions on how to investigate this further ? Thanks

### Steps to reproduce

Run in gke using 
```
    database:
      host: 10.53.*.*
      port: 5432
      driverClass: org.postgresql.Driver
      dbScheme: postgres
      databaseName: openmetadata_db
      auth:
        username: openmetadata_user
        password:
          secretRef: postgres-secrets
          secretKey: openmetadata-postgres-password
```

### Chart Version

1.3.2

### App Version

1.3.2

### Kubernetes Version

1.29.2-gke.1217000 

### Helm Version

v3.10.0

### Relevant Logs

```shell
Migrating the OpenMetadata Schema.
Failed to db migration due to
org.flywaydb.core.api.FlywayException: No database found to handle jdbc:postgres://10.53.*.*:5432/openmetadata_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
	at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForUrl(DatabaseTypeRegister.java:54)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1087)
	at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:636)
	at org.openmetadata.service.util.OpenMetadataOperations.parseConfig(OpenMetadataOperations.java:411)
	at org.openmetadata.service.util.OpenMetadataOperations.migrate(OpenMetadataOperations.java:208)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2066)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.openmetadata.service.util.OpenMetadataOperations.main(OpenMetadataOperations.java:500)
```

### Have you joined Openmetadata Slack community?

No

**Comment by mtk12** [comment]
Facing Similar issue any update on this

**Comment by mtk12** [comment]
Found the solution change dbScheme from postgres to postgresql
